version: '3.3'
services:
  pythonscript:
    restart: on-failure
    build: 
      context: ./Flask
      dockerfile: Dockerfile
    # ports: 
    #   - "5000:5000"
    depends_on: 
      - redis
    networks:
      - appnet
    container_name: pythonscript
  redis:
    image: redis:alpine
    networks:
      - appnet
    container_name: redis
  proxy:
    build: 
      context: ./Proxy
      dockerfile: Dockerfile
    depends_on: 
      - pythonscript
      - static
    ports: 
      - "80:80"
    networks: 
      - appnet
    container_name: proxy
  static:
    build: 
      context: ./Static
      dockerfile: Dockerfile
    container_name: static
    networks: 
      - appnet
networks:
  appnet:
    driver: bridge
